services:
  - type: web
    name: fastapi-todo-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    plan: free
    branch: main  # or whatever your Git branch is
